POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJ1a2V0a2FyYWthcyIsImlkIjoiNjFiM2I1MmEzMTg4NWZlMTI4MzQ1YWYwIiwiaWF0IjoxNjM5MTc0MzI5LCJleHAiOjE2MzkxNzc5Mjl9.jZf53JytfFs-f3VsDNN2bCQnJFaF814sdlAny0ADamQ

{
    "author": "Buket ghjghjgh",
    "title": "dhjghjgh University",
    "url": "dsadasd",
    "likes": 20
    }

###

DELETE http://localhost:3003/api/blogs/61b3c346aff85e26e2f95c62
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJ1a2V0a2FyYWthcyIsImlkIjoiNjFiM2I1MmEzMTg4NWZlMTI4MzQ1YWYwIiwiaWF0IjoxNjM5MTc1OTIwLCJleHAiOjE2MzkxNzk1MjB9.YphLKECAfTftA25qi2nSa2OulT2DB8xBIAOS1DqZEPA

###

PUT http://localhost:3003/api/blogs/61ab6c34e62aebe95b3195a4
Content-Type: application/json

{
    "title": "Hello world",
    "author": "Berk Karakaş",
    "url": "121",
    "likes": 10
}

