POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "author": "Buket Karakaş",
    "title": "Sabanci University",
    "url": "dsadasd",
    "likes": 20,
    "user": "61b3512e94ca6b1f6ce6277e"
}

###

DELETE http://localhost:3003/api/blogs/61b353a24e155134cbb761ca
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJ1a2V0a2FyYWthcyIsImlkIjoiNjFiM2I1MmEzMTg4NWZlMTI4MzQ1YWYwIiwiaWF0IjoxNjM5MTY3MzA1LCJleHAiOjE2MzkxNzA5MDV9.8sh95P4hTilhJfmR4PlTah1v4LVrG00IbPrusIZlMAk

###

PUT http://localhost:3003/api/blogs/61ab6c34e62aebe95b3195a4
Content-Type: application/json

{
    "title": "Hello world",
    "author": "Berk Karakaş",
    "url": "121",
    "likes": 10
}

